# code

In [44]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [49]:
d = pd.read_csv('SMSSpamCollection',sep='\t',names=['Status','Message'])
print(d.head());
print(len(d[d.Status=='spam']))
len((d[d.Status=='ham']))


  Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...
747


4825

In [27]:
x=d.Message
y=d.Status
d.loc[d["Status"]=='ham',"Status"]=1
d.loc[d["Status"]=='spam',"Status"]=0
d


Status                                            Message
0         1  Go until jurong point, crazy.. Available only ...
1         1                      Ok lar... Joking wif u oni...
2         0  Free entry in 2 a wkly comp to win FA Cup fina...
3         1  U dun say so early hor... U c already then say...
4         1  Nah I don't think he goes to usf, he lives aro...
5         0  FreeMsg Hey there darling it's been 3 week's n...
6         1  Even my brother is not like to speak with me. ...
7         1  As per your request 'Melle Melle (Oru Minnamin...
8         0  WINNER!! As a valued network customer you have...
9         0  Had your mobile 11 months or more? U R entitle...
10        1  I'm gonna be home soon and i don't want to tal...
11        0  SIX chances to win CASH! From 100 to 20,000 po...
12        0  URGENT! You have won a 1 week FREE membership ...
13        1  I've been searching for the right words to tha...
14        1                I HAVE A DATE ON SUNDAY WITH WILL!!
15        0  XXXMobileMovieClub: To use your credit, click ...
16        1                         Oh k...i'm watching here:)
17        1  Eh u remember how 2 spell his name... Yes i di...
18        1  Fine if that’s the way u feel. That’s the way ...
19        0  England v Macedonia - dont miss the goals/team...
20        1          Is that seriously how you spell his name?
21        1    I‘m going to try for 2 months ha ha only joking
22        1  So ü pay first lar... Then when is da stock co...
23        1  Aft i finish my lunch then i go str down lor. ...
24        1  Ffffffffff. Alright no way I can meet up with ...
25        1  Just forced myself to eat a slice. I'm really ...
26        1                     Lol your always so convincing.
27        1  Did you catch the bus ? Are you frying an egg ...
28        1  I'm back &amp; we're packing the car now, I'll...
29        1  Ahhh. Work. I vaguely remember that! What does...
...     ...                                                ...
5542      1           Armand says get your ass over to epsilon
5543      1             U still havent got urself a jacket ah?
5544      1  I'm taking derek &amp; taylor to walmart, if I...
5545      1      Hi its in durban are you still on this number
5546      1         Ic. There are a lotta childporn cars then.
5547      0  Had your contract mobile 11 Mnths? Latest Moto...
5548      1                 No, I was trying it all weekend ;V
5549      1  You know, wot people wear. T shirts, jumpers, ...
5550      1        Cool, what time you think you can get here?
5551      1  Wen did you get so spiritual and deep. That's ...
5552      1  Have a safe trip to Nigeria. Wish you happines...
5553      1                        Hahaha..use your brain dear
5554      1  Well keep in mind I've only got enough gas for...
5555      1  Yeh. Indians was nice. Tho it did kane me off ...
5556      1  Yes i have. So that's why u texted. Pshew...mi...
5557      1  No. I meant the calculation is the same. That ...
5558      1                             Sorry, I'll call later
5559      1  if you aren't here in the next  &lt;#&gt;  hou...
5560      1                  Anything lor. Juz both of us lor.
5561      1  Get me out of this dump heap. My mom decided t...
5562      1  Ok lor... Sony ericsson salesman... I ask shuh...
5563      1                                Ard 6 like dat lor.
5564      1  Why don't you wait 'til at least wednesday to ...
5565      1                                       Huh y lei...
5566      0  REMINDER FROM O2: To get 2.50 pounds free call...
5567      0  This is the 2nd time we have tried 2 contact u...
5568      1               Will ü b going to esplanade fr home?
5569      1  Pity, * was in mood for that. So...any other s...
5570      1  The guy did some bitching but I acted like i'd...
5571      1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [28]:
c=CountVectorizer()
x_c=c.fit_transform(["my name is pushpneet pushpneet singh","i am currently taking a session am"])
x_c.toarray()


array([[0, 0, 1, 1, 1, 2, 0, 1, 0],
       [2, 1, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [29]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [30]:
c1=CountVectorizer()
x_trainc1=c1.fit_transform(x_train)
x_trainc1.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [32]:
m=MultinomialNB()
m.fit(x_trainc1,y_train)



MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [33]:
x_testc1=c1.transform(x_test)
x_testc1.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
pre=m.predict(x_testc1)
pre

array([1, 0, 1, ..., 1, 0, 1])

In [43]:
print("Multinomial : {}".format(m.score(x_testc1,y_test)))

Multinomial : 0.9874439461883409
